language: python
python:
  - "2.7"
env:
  - DJANGO=1.3
  - DJANGO=1.4
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libarchive-dev
install:
  - pip install .
script:
  - make test
notifications:
  slack: smartfile:tbDIPzVJIPBpSz29kQw6b8RQ
